client/kubernetes.go, client/types.go
=> refactor: rename package to client

.gitignore, client/types.go
support generic in static mode
=> feat(config): support generic in static mode

client/types.go
feat(types): add inline and omitempty
=> feat(types): add inline and omitempty

aws/client/rds/rds.go
=> feat: add reboot for rds instance and cluster

aws/client/rds/rds.go
=> fix: fix rebootInstance and createCluster

aws/client/rds/rds.go
=> feat: add SetIOPS and SetEngineMode for rds cluster

kubernetes/api/v1alpha1/databaseclass.go, kubernetes/api/v1alpha1/databaseendpoint.go, kubernetes/api/v1alpha1/datashard.go, kubernetes/api/v1alpha1/qosclaim.go, kubernetes/api/v1alpha1/trafficstrategy.go
=> feat: add SchemeBuilder to workloads

kubernetes/api/v1alpha1/deepcopy.go, kubernetes/api/v1alpha1/trafficstrategy.go
=> feat: Add DeepCopy to TrafficStrategy, DataShard and QoSClaim

config/crd/bases/core.database-mesh.io_databaseendpoints.yaml, kubernetes/api/v1alpha1/databaseendpoint.go
=> chore: update DatabaseEndpoint status

config/crd/bases/core.database-mesh.io_databaseendpoints.yaml, kubernetes/api/v1alpha1/databaseendpoint.go
=> fix: column type

kubernetes/api/v1alpha1/databasechaos.go
=> feat: add annotations schedule time

kubernetes/api/v1alpha1/databasechaos.go
=> chore: fix DatabaseChaosList scheme

aws/client/rds/rds_test.go
=> chore: add rds test

kubernetes/api/v1alpha1/databaseclass.go
=> feat: add annotation for availabilityzones

aws/client/rds/rds.go
=> refactor: update rds client instance and cluster interface

aws/client/rds/rds.go
=> fix: fix context

aws/client/rds/rds.go
=> fix: fix interface

aws/client/rds/rds.go
=> chore: remove context of instance and cluster

aws/client/rds/rds.go
=> fix: add pitr initialization

aws/client/rds/cluster.go, aws/client/rds/instance.go, aws/client/rds/instance_test.go, aws/client/rds/rds.go
- Add some const of AWS Cluster status ref:https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/accessing-monitoring.html
- Add `DescribeSnapshot` to get instance snapshot info
=> add cluster status and add DescribeInstanceSnapshot

aws/client/rds/instance.go, aws/client/rds/instance_test.go
- Add func `SetFilter` to set filters for `DescribeDBInstancesInput`.
- Add func `DescribeAll` to return all instances of req.
=> feat: aws rds instance add SetFilter and DescribeAll

aws/client/rds/aurora.go
get / delete aurora  returns nil when aurora is not exist.
`DBClusterNotFoundFault` is not an error.
=> fix: returns err when describe/delete aurora and aurora is not exist

aws/client/rds/aurora.go, aws/client/rds/cluster.go, aws/client/rds/cluster_test.go, aws/client/rds/rds_suite_test.go
Update cluster status to `DBClusterStatus` type.
=> chore: update cluster status type

aws/client/rds/cluster.go, aws/client/rds/cluster_test.go
Add func `SetSkipFinalSnapshot` for aws rds cluster.
=> feat: aws cluster add SetSkipFinalSnapshot

aws/client/rds/cluster.go, aws/client/rds/cluster_test.go
- Add `SetFinalDBSnapshotIdentifier` of aws rds cluster for delete with final snapshot.
- Handle the error of DBClusterNotFound when get/delete aws rds cluster.
=> feat: add SetFinalSnapshot and handler notfound error of aws rds cluster

aws/aws.go, aws/client/rds/aurora_test.go, aws/client/rds/cluster_test.go, aws/client/rds/instance_test.go, aws/client/rds/rds_suite_test.go, aws/client/rds/rds_test.go, aws/client/s3/bucket_test.go, aws/client/s3/object_test.go, aws/client/s3/s3_suite_test.go
Rename `accessKey` to `accessKeyId` and `secretKey` to `secretAccessKey`
=> chore(aws): rename aws credential keys
